FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Set environment variables
ENV REACT_APP_API_URL=http://localhost:5001

# Start the app in development mode
CMD ["npm", "start"]
