steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fait-444705/pointcounterpoint-backend', './backend']

  # Push the backend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fait-444705/pointcounterpoint-backend']

  # Deploy backend to Cloud Run with increased timeout and concurrency=1 for debugging
  # Deploy backend to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pointcounterpoint-backend'
      - '--image=gcr.io/fait-444705/pointcounterpoint-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=SUPABASE_URL=https://ueqselkevtzpzgcapbzc.supabase.co'
      - '--update-secrets=OPENAI_API_KEY=openai-api-key:latest,NEWS_API_KEY=news-api-key:latest,SUPABASE_KEY=supabase-key:latest'
      - '--timeout=5m'
      - '--concurrency=1'
      - '--cpu=1'
      - '--memory=512Mi'

  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fait-444705/pointcounterpoint-frontend', './frontend']

  # Push the frontend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fait-444705/pointcounterpoint-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pointcounterpoint-frontend'
      - '--image=gcr.io/fait-444705/pointcounterpoint-frontend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/fait-444705/pointcounterpoint-backend'
  - 'gcr.io/fait-444705/pointcounterpoint-frontend'