steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-perspectives-backend', './backend']

  # Push the backend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-perspectives-backend']

  # Deploy backend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'news-perspectives-backend'
      - '--image=gcr.io/$PROJECT_ID/news-perspectives-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=MONGODB_URI=MONGODB_URI:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest'

  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-perspectives-frontend',
           '--build-arg', 'REACT_APP_API_URL=https://news-perspectives-backend-fait-444705.a.run.app',
           './frontend']

  # Push the frontend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-perspectives-frontend']

  # Deploy frontend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'news-perspectives-frontend'
      - '--image=gcr.io/$PROJECT_ID/news-perspectives-frontend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/news-perspectives-backend'
  - 'gcr.io/$PROJECT_ID/news-perspectives-frontend'

substitutions:
  _MONGODB_URI: ${_MONGODB_URI}
  _OPENAI_API_KEY: ${_OPENAI_API_KEY}

options:
  logging: CLOUD_LOGGING_ONLY
