steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fait-444705/pointcounterpoint-backend', './backend']

  # Push the backend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fait-444705/pointcounterpoint-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pointcounterpoint-backend'
      - '--image=gcr.io/fait-444705/pointcounterpoint-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=OPENAI_API_KEY=${_OPENAI_API_KEY},NEWS_API_KEY=${_NEWS_API_KEY},SUPABASE_URL=https://ueqselkevtzpzgcapbzc.supabase.co,SUPABASE_KEY=${_SUPABASE_KEY}'

  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fait-444705/pointcounterpoint-frontend', './frontend']

  # Push the frontend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fait-444705/pointcounterpoint-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pointcounterpoint-frontend'
      - '--image=gcr.io/fait-444705/pointcounterpoint-frontend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _OPENAI_API_KEY: ''
  _NEWS_API_KEY: ''
  _SUPABASE_KEY: ''

images:
  - 'gcr.io/fait-444705/pointcounterpoint-backend'
  - 'gcr.io/fait-444705/pointcounterpoint-frontend'